- id: doi:10.1038/s41598-022-27175-x
  image: /images/scientificreports2023.png
  tags:
    - mass spectrometry
    - collaboration
    - CORNETT LAB
- id: doi:10.1126/science.aar7854
  image: 
  tags:
    - EVANs POSTDOC PAPERS

  - id: doi:10.1126/sciadv.aav2623
  image: 
  tags:
    - EVANs POSTDOC PAPERS

  - id: doi:10.1016/j.molcel.2018.08.015
  image: 
  tags:
    - EVANs POSTDOC PAPERS
