- id: doi:10.1038/s41598-022-27175-x
  image: /images/scientificreports2023.png
  tags:
    - cornett lab
    - mass spectrometry

- id: doi:10.1038/s41467-019-10324-8
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.1126/sciadv.aav2623
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.1016/j.molcel.2018.08.015
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.1038/s41467-019-10324-8
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.1126/science.aar7854
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.1126/sciadv.aav2623
  image: /images/2019_f1.jpeg
  tags:
    - KOPL
    - evans postdoc papers
    - VAI

- id: doi:10.1073/pnas.1806373115
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.1093/nar/gky151
  tags:
    - evans postdoc papers
    - VAI

- id: doi:10.3791/55912
  tags:
    - evans postdoc papers
    - VAI
    
- id: doi:10.1016/j.jbc.2023.104651
  image: /images/prdm9.png
  tags:
    - cornett lab
    


- id: doi:10.1126/sciadv.adk4423
  tags:
    - collaboration
    - VAI
